apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: srinivasedugutta/oct302025project:v1  # âœ… Your DockerHub image
          imagePullPolicy: Always                     # ensures it pulls the latest from DockerHub
          ports:
            - containerPort: 8080                     # your Spring Boot app port
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080                                # fixed port for NodePort access
  type: NodePort
